logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
#    root: trace

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/budget
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  cookie: jwt
  signing.key: 4aecd426ba172ab96f93649c37f17572abfb4d1ed7120252f5228d66c1a1d951
  # 1000 * 60 * 100 = 100min
  expiration: 6000000
  refresh:
    expiration: 60000000
    cookie: jwt-refresh

logging.level:
  com.budget.project: DEBUG
spring.graphql.graphiql.enabled: true

cors:
  origins: http://localhost:4200