spring.datasource:
  url: jdbc:h2:file:./localdb;AUTO_SERVER=TRUE
  driverClassName: org.h2.Driver
  username: sa
  password: password
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    root: WARN
    org.springframework.security: WARN
jwt:
  # 1000 * 60 * 1 = 1min
  expiration: 60000
  refresh:
    #1000 * 60 * 1000 = 1000min
    expiration: 60000000